[build]
builder = "nixpacks"

[build.nixpacks]
installCmd = "npm install"
buildCmd = "npm run build"
startCmd = "npm start"

[deploy]
startCommand = "npm start"
healthcheckPath = "/"
healthcheckTimeout = 300
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 10
region = "asia-southeast1"
